### ISSUE TITLE
relay sends errors to stdout, not sterr

### ISSUE THREAD

**Issue by ahpook** [puppetlabs/relay#32]
## Describe the Bug
When `relay` encounters an error, it writes to stdout. This can cause a problem if output is redirected by the shell as the error will be hidden or intermingled with the output stream.

## Expected Behavior
Errors should go to stderr so they are still visible when output is redirected

## Steps to Reproduce
1. As an authenticated user, run `relay workflow download nosuchworkflow > output.yaml`
2. Notice that you get a generic usage error on stderr, but the real error is written into the `output.yaml` file

```shell
> ./bin/relay-v3.5.4-25-g7ead845-darwin-amd64 workflow download relay-cli-update-brew2 > ./error.yaml
Usage:
  relay workflow download [workflow name] [flags]

Flags:
  -h, --help   help for download

Global Flags:
  -d, --debug        print debugging information
  -o, --out string   output type: (text|json) (default "text")
  -y, --yes          skip confirmation prompts

> bat -p error.yaml
Error:could not find record(s) matching query
```

**Comment by bradhe** [comment]
I patched this as part of [a recent commit](https://github.com/puppetlabs/relay/commit/4fd194e02672a819c84f84766bf83d7b277a5a88) but failed to mention this issue!

**Comment by ahpook** [comment]
Verified! I just neglected to close this.
