### ISSUE TITLE
Strange terminal handling on error output

### ISSUE THREAD

**Issue by ahpook** [puppetlabs/relay#34]
## Describe the Bug
The escape codes that print the colorized error messages under `relay workflow` are having a hard time displaying correctly on my terminal. Under oh-my-zsh the Error message is swallowed completely and doesn't show up; i only see the usage screen. Under vanilla bash, it shows up but is splatted together with the next command prompt (see screenshot).
Could be related to #32 , maybe the escape sequences from one fd are getting clobbered by the other?

## Expected Behavior
ideally it'd show the exact error from the service. If there's a clear error from the service (rather than a missing subcommand/wrong command syntax), maybe it should _only_ show that error and not the usage message...?

## Steps to Reproduce
1. try to fetch a nonexistent workflow with `relay workflow download sfsfsf`

**Comment by bradhe** [comment]
@ahpook can you see if this is reproducible from the patched branch in #31 ?

**Comment by ahpook** [comment]
Yeah, still seeing it even with 4fd194e02 applied. It could be hyper local to my setup, I'll poke at it a bit further on my own. Not a blocker

**Comment by ahpook** [comment]
This is also now fixed in #31 w/ the usage-on-error turned off.

**Comment by ahpook** [comment]
```
bin/relay-v3.5.4-32-g9d2b7ea-darwin-amd64 workflow download sfsfsf
Error:could not find record(s) matching query
```

**Comment by ahpook** [comment]
![Screenshot 2020-05-06 16 41 56](https://user-images.githubusercontent.com/56753/81347225-92b08400-9070-11ea-85ca-e7ea8a1211da.png)

Realized I'd referenced a screenshot above but forgotten to actually attach it 🤦‍♂️
