### ISSUE TITLE
Don't display usage when there's a service error

### ISSUE THREAD

**Issue by ahpook** [puppetlabs/relay#35]
## Describe the Bug
In several places in the app, when there's an error interacting with the service we display the error message alongside the usage/help text for the command the user ran. 

## Expected Behavior
Usage/help should only display when the user had a syntax error in the command or asked for help directly. When there's an actionable, direct error from the program or the service that ought to be the only output.

## Steps to Reproduce
Places I found this:
* `relay auth login eric@puppet.com` with a wrong password
* `relay workflow download sfsfs` with a nonexistent workflow name
* `relay workflow replace sfsffs -f workflow.yaml` with a non-existent workflow on service
* `relay workflow add blah -f nothing` with a nonexistent local path

**Comment by nmuldavin** [comment]
This is going to be a hard one to fix, unfortunately. It bubbles up from the CLI framework we're using, which shows usage whenever there's an error at all and can only be turned off entirely

**Comment by bradhe** [comment]
This actually was pretty easy. The `SilenceUsage` setting is a bit of a misnomer. It silences usage when an error occurs!

**Comment by ahpook** [comment]
Yep, verified that 9d2b7ea fixes this! Nice work 🥇
