### ISSUE TITLE
Push trigger endpoint returns 200 {"success":true} with an incorrect token

### ISSUE THREAD

**Issue by timidri** [puppetlabs/relay#44]
## Describe the Bug
Push trigger endpoint returns 200 {"success":true} when an incorrect token is used.

## Expected Behavior
A 401 Unauthorized with {"success":false} or something with similar semantics.

## Steps to Reproduce
1. Create a push trigger for a workflow
2. Issue a request for the trigger using a wrong token
3. Observe a 200 {"success":true} response

## Environment
 - Version [e.g. 0.1.0]

**Comment by ahpook** [comment]
I was able to verify/reproduce this. @impl i'm going to assign to you for now but feel free to reassign - related JIRA is PN-948
