### ISSUE TITLE
As a workflow author, I want be able to add a step into my workflow from a list of steps in the UI

### ISSUE THREAD

**Issue by timidri** [puppetlabs/relay#45]
## Use Case
As a workflow author, I want to be able to add a step to my workflow from a list of curated steps in the UI.
Currently, I need to search for documentation of the step, and if no documentation is present, I don't know how to use the step.

## Describe the Solution You Would Like
I would like to see a menu "Add Step" in the UI and when clicked, to open a list of curated steps. When I click a step, that step is added to my workflow, using a metadata/skeleton/template which should be published along with the step. I would also like to see which outputs the step generates.

## Describe Alternatives You've Considered
n/a

## Additional Context
As a stretch goal, I would like to be able to add other repositories of custom steps to the UI's "Add Step" menu.

**Comment by ahpook** [comment]
@timidri - This is a cool idea but honestly it is a long ways out from a roadmap standpoint! We are going to focus on authoring as a code-first / terminal-first experience to make sure it is easy and fun to make content before going in on this kind of graphical workflow builder.

**Comment by ahpook** [comment]
I'm going to assign to @kenazk for backlog info but close the issue since it's not actively being worked on.

**Comment by timidri** [comment]
@ahpook Understand. However, the same problem exists in a terminal-first world. Is it possible to add `relay step list [repo]` to the command set? And add a mandatory spec file to each step so steps start auto-documenting how to use them?

**Comment by kenazk** [comment]
@timidri I agree we want to make some progress here. Please follow along on PN-900. I'll be tracking this work there.
