### ISSUE TITLE
Workflow schema not working with VS Code.

### ISSUE THREAD

**Issue by bryanjbelanger** [puppetlabs/relay#48]
## Describe the Bug
Error Returned:

Unable to parse content from 'https://github.com/puppetlabs/relay-core/blob/development/pkg/workflow/asset/data/schemas/v1/Workflow.json': Parse error at offset 5.(768)

## Expected Behavior
Would like plugin to work and validate my relay yaml.

## Steps to Reproduce
Add standard json to `settings.json`.

Mine looks like this:

``` json
{
    "explorer.confirmDragAndDrop": false,
    "editor.minimap.enabled": false,
    "git.autofetch": true,
    "git.enableSmartCommit": true,
    "explorer.confirmDelete": false,
    "git.confirmSync": false,
    "terminal.integrated.shell.osx": "/bin/zsh",
    "yaml.schemas": {
        "https://github.com/puppetlabs/relay-core/blob/development/pkg/workflow/asset/data/schemas/v1/Workflow.json": ["relay*/*.yaml"]
    },
    "yaml.customTags": [
        
        
        "!Secret scalar",
        "!Parameter scalar",
        "!Output sequence",
        "!Answer sequence",
        "!Data scalar",
        "!Connection map",
        "!Fn.append sequence",
        "!Fn.concat sequence",
        "!Fn.equals sequence",
        "!Fn.jsonUnmarshal sequence",
        "!Fn.notEquals sequence",
        "!Fn.merge sequence",
    ],
    "yaml.validate": true
}
```

## Environment
 - VSCode 1.46.1
- OSX Catalina

## Additional Context
- None

**Comment by ahpook** [comment]
Whoops, I used the human-facing URL for the workflow schema - that should be: 

https://raw.githubusercontent.com/puppetlabs/relay-core/master/pkg/workflow/asset/data/schemas/v1/Workflow.json

**Comment by ahpook** [comment]
Pushed a commit and this should go out on the next website build, thanks for the report @bryanjbelanger !! 💯
