### ISSUE TITLE
Clicking "back" from "view logs" does not re-render the graph

### ISSUE THREAD

**Issue by nmaludy** [puppetlabs/relay#72]
## Describe the Bug

After running a workflow, and viewing the logs for a step, clicking "back" in my browser leaves the middle pane blank where the graph should be rendered.

## Expected Behavior
I expected to go back to the graph view where i was before.

## Steps to Reproduce
1. Run a workflow (in my case it was the t-shirt workflow)
2. Click on one of the steps 
3. Click on "View logs for this step"
4. Click the "Back" button in your browser. You will be moved back to the graph page, but there is no graph rendered

![image](https://user-images.githubusercontent.com/3693851/98023030-5ae28900-1dd4-11eb-9e9a-c088ba393f8e.png)

## Environment
 - Version ??
 - Platform: CentOS 7, Firefox 82.0.2
 - Platform: CentOS 7, Chrome 86.0.4240.111

**Comment by ahpook** [comment]
@vine77 this looks similar to what we were seeing from fullstory sessions last week. wdyt?

**Comment by vine77** [comment]
It's possible it's a different issue (completely blank instead of blank after trigger...) with use of browser back button. I couldn't reproduce, but we can keep this open for now.
