### ISSUE TITLE
Unable to update password through web interface

### ISSUE THREAD

**Issue by obowersa** [puppetlabs/relay#83]
## Describe the Bug
When attempting to update my password through the web interface, a blank error appears

## Expected Behavior
Password update to be successful, or information on why the error has appeared

## Steps to Reproduce
1. Go to email address in bottom left hand corner of the web interface
2. Input existing password and new password
3. Click update password

## Environment
 - Chrome version 88.0.4324.190 (Official Build) (64-bit)
 
 
![image](https://user-images.githubusercontent.com/3088689/109407751-5f324380-797b-11eb-8d8e-68dbaef392bc.png)

**Comment by hunner** [comment]
Thanks for reporting this bug! It appears that the profile-page password-change form is left over from our previous authentication mechanism. We will update it for the newer system.

In the mean time, as a workaround you can use the "Don't remember your password?" link at the login page to change (reset) your password. Just log out, and you should be presented with this prompt:
![image](https://user-images.githubusercontent.com/91972/109540143-f3350580-7a76-11eb-886f-e240e4bd28c8.png)
